# User an official node.js runtime as a parent image - 
# Image - Snap shot of seperate instruction sheet. when we build our container, we are creating a snapshot of that enviroment 

FROM node:22-alpine